spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?&useUnicode=true&characterEncoding=UTF8
    username: root
    password: jin0792
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.kiway.spring.swagger.springswagger.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081



